### PR TITLE
fix(canvas): every block layout an agent can produce renders unbroken in the workspace column — gallery test + fixes (#2583)

### LINKED ISSUE #2583: bug(canvas): every block layout an agent can produce renders unbroken in the workspace column — gallery test + fixes
## Summary

The canvas has a rich block vocabulary (ent#536), but it has only ever been looked at through a handful of hand-made canvases. #2581 found that the **first real agent-produced canvas rendered broken** — blocks not laid out in a clean single column, and the column overflowing its width. One broken canvas out of the first few tried is not a single defect; it is an untested render surface.

This issue owns **only the rendering**: take the canvas through *dozens* of different block layouts — every kind, every chart type, every rich fence, and the adversarial shapes an agent will eventually emit — displayed in the **vertical workspace column**, and make each one land correctly. Where a layout breaks, fix the renderer so that class of payload cannot break it again.

**Extracted from #2581.** That issue keeps the voice-mode halves — the missing post-call transcript and the call-mode column split. This one is the UI-only, vocabulary-wide render bar; the two are worked independently.

## Context

The canvas renders through **one** component (`CanvasPanel`) on three surfaces — the Workspace rail Canvas tab (`PortalRailCanvas.vue`), the Workspace agent page (`PortalAgentPage.vue`), and the Agent Detail Canvas tab (`AgentCanvasTab.vue`) — so a fix made once holds everywhere, and a defect missed once is visible everywhere. The narrowest of those, the rail column, is where the layout bar actually bites: the canvas must be *good looking* in a tall, narrow, vertical column, not only in a wide page.

The existing coverage (`e2e/ent438-agent-canvas.spec.js`) asserts that four kinds appear at all. Nothing asserts that they are laid out correctly, that a wide table does not push the page sideways, or that a malformed payload degrades instead of blanking the panel.

**"Unbreakable" is the design-system contract applied to author-controlled content** (`docs/memory/design-system-contract.md`): a block is bounded by its column, unbounded data scrolls *inside its own block*, the page never scrolls horizontally, both themes are first-class, and a payload the renderer cannot make sense of degrades honestly (named reason, JSON fallback) instead of rendering blank or throwing and taking the panel with it.

**Not in scope:** new block kinds, new fences, or changes to the write path / agent prompt guidance. This is render-hardening of the vocabulary that already exists.

## The matrix to cover

Block kinds (`canvasUtils.js`): `table`, `kpi`, `markdown`, `timeline`, `json` (report-delegated) + `chart`, `html`, `image`, `diagram` (canvas-only).

| Dimension | Cases |
|---|---|
| Chart types | `line`, `area`, `bar`, `stacked_bar`, `pie`, `donut` — plus 12-series (palette wrap), single point, all-zero, negative values, missing/null points, long series names |
| Markdown rich fences | `chart`, `kpi`, `table`, `mermaid` inside markdown, several in one block, a fence with a broken body |
| Table | 2 cols vs 12 cols; 200 rows; a 60-char unbroken token in a cell; empty cells; numeric alignment |
| Text | 4000-char paragraph, unbroken URL, CJK, RTL, emoji, a heading-only block |
| Diagram | short flowchart, a 20 000-char source (`CANVAS_DIAGRAM_MAX_CHARS`), a Mermaid source that fails to parse |
| Image | wide landscape, tall portrait, tiny, workspace path that 404s, a refused source |
| html | the voice panel's `update_panel` output, including a long unwrapped line |
| Canvas-level | 1 block, 50 blocks (`CANVAS_MAX_BLOCKS`), a payload near 512 KiB, blocks of mixed kinds interleaved |
| Degradation | unknown kind, kind/payload mismatch, empty payload, `null` fields |

## Acceptance Criteria

- [ ] A **canvas gallery fixture** exists (≥ 12 canvases, ≥ 40 distinct block configurations covering the matrix above), seeded through the **real write path** (`PUT/PATCH /api/agents/{name}/canvas/{canvas_id}`) — not by mounting components with hand-made props — so what is tested is what an agent can actually produce.
- [ ] **Real agent output is part of the evidence, not only the fixture**: at least three canvases asked for from chat in plain language ("dashboard of X", "report with a chart and a table", "diagram of Y") render correctly; screenshots attached to the PR.
- [ ] **No page-level horizontal overflow** on any gallery canvas, in the rail column and full-width surfaces, at 1280 / 1440 / 1920 px and on resize. Wide content (tables, code, diagrams, images, charts) scrolls inside its own block or shrinks to the column.
- [ ] Blocks lay out in **one vertical column** with the kit's spacing on all three surfaces; no block overlaps, clips, or bleeds into its neighbour; no block collapses to zero height.
- [ ] **Light and dark are both correct** for every case — semantic tokens only; `node src/frontend/scripts/scan-raw-colors.mjs src/frontend` does not raise any per-file count over `src/frontend/raw-color-baseline.json`.
- [ ] **Honest degradation**: an unknown kind, a kind/payload mismatch, a malformed fence, or a failing Mermaid parse renders a named fallback (JSON view / reason line) — never a blank block, never a thrown render error that empties the whole panel. One bad block does not stop the good blocks around it from rendering.
- [ ] **Layout stability**: switching canvases, or blocks arriving/refreshing, does not reset scroll position or reflow the surrounding page; the panel reserves space rather than gating the whole surface on a loading flag (`utils/loadingState.js::viewState`).
- [ ] **Playwright coverage** for the gallery: renders at two viewport widths × both themes, asserting no horizontal document overflow and per-block bounding boxes inside the column; screenshots produced as artefacts.
- [ ] Every defect found gets a **regression test** naming its payload class, so the same shape cannot silently return.
- [ ] Findings are recorded: a short table in the PR of "layout tried → what broke → what fixed it", so the render bar is inspectable afterwards.

## Technical Notes

- Renderers: `src/frontend/src/components/canvas/{CanvasPanel,CanvasBlock,CanvasChart,CanvasPieChart,CanvasDiagram,CanvasImage,CanvasMarkdown}.vue`, `canvasUtils.js` (`CANVAS_BLOCK_KINDS`, `CHART_TYPES`, `RICH_FENCES`), `src/frontend/src/utils/canvasPalette.js`.
- Surfaces: `components/portal/PortalRailCanvas.vue` (narrow rail column — the hard case), `components/portal/PortalAgentPage.vue`, `components/canvas/AgentCanvasTab.vue`.
- Report-delegated kinds render through `components/reports/ReportRenderer.vue` — a fix there is shared with reports; keep `shapeOk` inside that component (#1535, #2162).
- Write path / limits: `src/backend/routers/canvas.py`, `services/canvas_blocks.py`, `models.py` (`CANVAS_MAX_BLOCKS=50`, `CANVAS_BLOCKS_MAX_BYTES=512 KiB`, `CANVAS_DIAGRAM_MAX_CHARS=20000`, `CANVAS_IMAGE_INLINE_MAX_BYTES=64 KiB`).
- Existing coverage to extend, not duplicate: `src/frontend/e2e/ent438-agent-canvas.spec.js`, `src/frontend/tests/unit/canvasUtils.spec.js`.
- Bound by `docs/memory/design-system-contract.md`; loading-gate ratchet `src/frontend/loading-gate-baseline.json`.
- Related: #2581 (parent observation, keeps the voice-mode halves), abilityai/trinity-enterprise#536 / #537 (vocabulary, fences, design kit), abilityai/trinity-enterprise#438 (canvas surface).

### PR DESCRIPTION
**Pull request by trinity-ability**
## Summary

**Surfaces:** Agent Detail (1280 / 1920), the Workspace rail (24rem), and the **Workspace voice-call column** (`e2e/canvas-gallery-voice.spec.js` — mocks only the call plumbing: start request, audio socket, panel read, roster capability; the real `PortalVoiceCanvas` mounts on the real page and switches boards on a panel-tool `tool_result` frame). 10 cells, ~50s.

A **measured render bar** for the canvas. `e2e/helpers/canvas-gallery.js` seeds 17 canvases / ~180 blocks through the real `PUT /api/agents/{name}/canvas/{id}` route — every kind, every chart type, the rich fences, the kit classes, the four starter layouts, and the adversarial shapes an agent will eventually emit (200-row tables, 60-char tokens, twelve series, 20,000-char Mermaid, `width: 9999px`, CJK/RTL, non-string payloads). `e2e/canvas-gallery.spec.js` renders each on Agent Detail (1280 / 1920) and the Workspace rail (fixed 24rem column), light and dark, and asserts per block: no horizontal scroll on the page or the kit, block inside the kit, drawing kinds drew something, no box **or text** spill without an owning scroll container, no sibling overlap. (counts above)

## Layout tried → what broke → what fixed it

| Layout | What broke | Fix |
|---|---|---|
| A canvas with ≥3 diagrams | 8 of 11 diagrams **empty** — `CanvasDiagram`'s "module" counter + render chain were in `<script setup>`, so they were per-instance; every diagram was `canvas-mmd-1` and mermaid's `render()` deleted the previous SVG from the page | shared state in a plain `<script>` block (`CanvasDiagram.vue`) |
| 40-node LR flowchart | scaled to a 3px strip | natural width + scroll (`keepLegibleWidth`) |
| 20k-char Mermaid over the edge limit | 10,000px red error box | error box bounded (`max-h-72`) |
| `markdown: 42`, a timeline with a `null` event | the **whole block vanished** (leaf threw, section unmounted) | `CanvasBlock` is an error boundary → JSON in place; prose only for strings |
| 200-row table, 40-event timeline | 8,000px surface | 420px scroll viewport on the canvas (kit's `ck-table-wrap` bound) |
| KPI tiles in the rail | 4 × 80px tiles (`lg:` is the viewport, the rail is 24rem) | `.report-kpi-grid` re-flows by the kit's `@container` |
| Unbroken URL / 60-char token in prose, html, KPI value | spilled past the column | `overflow-wrap: anywhere` on canvas prose/html/tiles |
| 10-col markdown table, bare `<table>` in the rail | pushed the column / then one-letter-per-line cells | prose tables are their own scroll viewport; cells wrap by word |
| `width: 9999px` on a card | canvas scrolled 10,000px sideways | `filterInlineStyle` emits `min(<px>, 100%)` |
| 12-series line chart | no legend — unreadable without hover | legend under multi-series line/area |
| All-zero series, single point | blank plot (degenerate `[v, v]` range) | padded range; isolated points drawn via `points.filter` |
| 30 category labels | overprinted | `axisLabelSpace` → uPlot `space` |
| Pie in a narrow figure cell | legend labels all ellipsis | legend wraps under the pie |
| Switching canvases quickly | header named one canvas, blocks belonged to another (slower fetch won) | sequence guard in `CanvasPanel.select` |
| **Voice call, 1280px** (the #2581 column) | page 296px wider than the viewport — `w-[40%]` + `w-[60%]` beside the 18rem sidebar = 100% + 18rem, clipped by the shell's `overflow-hidden` with no scrollbar | orb and canvas are flex shares of a zero basis (2 : 3) — 40/60 of the space *beside* the sidebar |
| `kpi` block in a layout's grid slot (voice column) | four 45px tiles, "OPE / N" wrapped inside | every block is a `@container`; kit grids + KPI grid collapse on the block's width |

Refused **by the write route** (a named 422/400, so unseedable — unit-covered instead): an unknown `kind`, a diagram with blank source.

## Not changed (on purpose)

- No new kinds, fences, layouts, or write-path changes — render hardening of the existing vocabulary only.
- `StackedBarChart` draws no value axis (numbers only in the legend totals) and timeline `ts` prints the raw ISO string — both readable, both shared with reports; left as follow-ups.
- The portal canvas detail route is limited to 60 reads/min per agent; the spec is written to stay under it (one navigation per test). A person clicking through 17 canvases twice in a minute would hit it too — noting, not changing.

## Test plan

- [x] `npx playwright test e2e/canvas-gallery.spec.js e2e/canvas-gallery-voice.spec.js` against a live stack (`ADMIN_PASSWORD`, `E2E_BASE_URL`, `CANVAS_AGENT` = any agent, default `test-harness-agent`; `KEEP_GALLERY=1` to leave the canvases up for inspection) — 10/10 pass; screenshots in `e2e/canvas-gallery-shots/` (gitignored)
- [x] `npm run test:unit` — 2243 pass (incl. the loading-gate ratchet); new cases for `axisLabelSpace` / `trendChartProps.labelSpace`, updated `filterInlineStyle` expectations
- [x] `node src/frontend/scripts/scan-raw-colors.mjs src/frontend` — no per-file count grew
- [x] Visual pass over the light and dark renders of every gallery canvas on both surfaces
- [ ] **Real agent output** (issue AC): three canvases asked for from chat on a running agent — needs a live agent with a model; not exercised in this PR, please verify on dev

Fixes #2583

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_01Fg8PsfHGoivCttFzDDCKfT

### CODE REVIEW

**Review by vybe — APPROVED** [review]
Validated via /validate-pr. Fixes #2583 (P1 bug, theme-ui-ux). Feature flow updated (agent-canvas.md), e2e gallery + voice specs plus unit specs, named regression coverage. Sanitization posture preserved: the min(<px>, 100%) wrap in canvasKit.js is applied to our own string after the value already matched the bounded-shape allowlist, and CanvasDiagram still routes v-html through sanitizeSvg. Render-sequence guard prevents stale async mermaid renders. All checks green.

Minor, non-blocking: CanvasChart.vue's new legend adds one net-new raw palette pair (text-gray-600 dark:text-gray-300) where the design-system contract asks for semantic tokens. Every other raw-color line in this diff is a moved pre-existing line.
