### PR TITLE
fix(tests): evict the whole git_service package family — 13 leaked failures in test_ent615 (0.9.5 M1)

### LINKED ISSUE #2859: test isolation: dev push unit suite red since #2487, 13 test_ent615_token_free_remotes failures from tests that reset services.git_service without its submodules
## Summary

The `pytest (push, absolute failures)` job in `backend-unit-test` has been red on every `dev` push since `5c4dc4b2a` (#2487, the #1028 split of `services/git_service.py` into a package, 2026-09-16). All 13 failures are in `tests/unit/test_ent615_token_free_remotes.py`. They are order-dependent: the file passes on its own (89 passed), and four other test files each make it fail when they run first. The product code is fine. The defect is test isolation.

## Failing tests

All 13 fail with `AttributeError: module 'services.git_service' has no attribute 'token_scrub'`, except the two `TestDegradesHonestly` tests, which fail with `... no attribute 'conflicts'`.

```
test_ent615_token_free_remotes.py::TestAnUnreadableSweepReachesAnOperator::test_it_alarms_when_the_sweep_could_not_look
test_ent615_token_free_remotes.py::TestAnUnreadableSweepReachesAnOperator::test_it_stays_quiet_on_an_ordinary_clean_pass
test_ent615_token_free_remotes.py::TestDegradesHonestly::test_a_bare_403_is_NOT_treated_as_an_auth_failure
test_ent615_token_free_remotes.py::TestDegradesHonestly::test_the_marker_is_classified_as_an_auth_failure
test_ent615_token_free_remotes.py::TestInitializeSeedsRatherThanOrphaning::test_a_supplied_pat_is_seeded_before_any_remote_is_written
test_ent615_token_free_remotes.py::TestInitializeSeedsRatherThanOrphaning::test_a_tokenless_agent_is_not_failed
test_ent615_token_free_remotes.py::TestInitializeSeedsRatherThanOrphaning::test_it_fails_honestly_when_the_credential_cannot_be_placed
test_ent615_token_free_remotes.py::TestRotationWithoutARecreate::test_update_remote_pat_writes_the_env_file_over_docker_exec
test_ent615_token_free_remotes.py::TestTheCredentialNeverTouchesArgv::test_nothing_is_re_pointed_when_no_credential_resolves
test_ent615_token_free_remotes.py::TestTheCredentialNeverTouchesArgv::test_the_env_write_and_the_sweep_run_as_root
test_ent615_token_free_remotes.py::TestTheCredentialNeverTouchesArgv::test_the_re_pointed_origin_is_credential_less
test_ent615_token_free_remotes.py::TestTheCredentialNeverTouchesArgv::test_the_sweep_is_bounded_in_the_container_too
test_ent615_token_free_remotes.py::TestTheCredentialNeverTouchesArgv::test_update_remote_pat_carries_the_token_in_the_exec_environment
```

The same 13 IDs appear on three `dev` push runs: `5c4dc4b2a` (run 35116218599), `4196a6d52` (run 35151192819) and `3a47f7440` (run 35203443016). The last green push run was `888c3866a`, the commit before #2487.

## Test files that cause it

Each file below, run immediately before the ent615 file with random ordering off, reproduces all 13 failures on `dev` @ `3a47f7440`:

| Test that runs first | Result with `test_ent615_token_free_remotes.py` after it |
|---|---|
| `tests/unit/test_1704_git_service_plugins.py` | 13 failed, 89 passed |
| `tests/unit/test_data_paths_allowlist.py` | 13 failed, 88 passed |
| `tests/unit/test_data_paths_gitignore.py` | 13 failed, 80 passed |
| `tests/unit/test_2075_detect_git_dir.py` | 13 failed, 88 passed |

Six other files that also stub `services.git_service` do **not** cause it, because they use `patch.dict(sys.modules, ...)` or `monkeypatch`, which restore the original entry: `test_1484_create_agent_characterization`, `test_ent109_git_env_seam`, `test_ent123_tokenless_clone`, `test_ent128a_catalog_resilience`, `test_fork_to_own`, `test_1759_local_template_not_found`.

### Repro

```bash
cd tests
python -m pytest -q -p no:randomly unit/test_ent615_token_free_remotes.py                 # 89 passed
python -m pytest -q -p no:randomly unit/test_1704_git_service_plugins.py \
                                   unit/test_ent615_token_free_remotes.py                 # 13 failed
```

## Mechanism

Before #1028, `services.git_service` was a single module, so `sys.modules.pop("services.git_service", None)` removed all of it. It is now a package, and that call removes only the package entry. Its submodules (`services.git_service.token_scrub`, `.conflicts`, ...) stay in `sys.modules`.

On the next `import services.git_service`, Python creates a new package object and runs its `__init__.py`. That `__init__` does `from .token_scrub import ...`, which finds the submodule already in `sys.modules`. Python binds a submodule as an attribute of its parent only when it first loads the submodule, so the new package never gets a `token_scrub` attribute. The ent615 fixture then reads `gs.token_scrub`, `gs.remotes`, `gs.gitignore` and `gs.conflicts`, and each read raises `AttributeError`.

The same thing happens with a plain two-file package:

```
first import, has sub: True
after pop(pkg) + reimport, has sub: False | pkg.sub still cached: True
```

The four files fail in two ways:
- `test_1704_git_service_plugins.py`, `test_data_paths_allowlist.py` and `test_data_paths_gitignore.py` call `sys.modules.pop("services.git_service", None)`. Only the package key is removed.
- `test_2075_detect_git_dir.py` clears every `services.git_service*` key. But it records only the package key for undo, so teardown removes the package and leaves behind the submodules the test imported.

Several files already clear the package and its submodules correctly with `k.startswith("services.git_service")` and restore them afterwards, for example `tests/unit/test_github_init_push.py`.

## Why PR CI didn't catch it

The seeded per-PR jobs run with `|| true`, and the workflow fails only on the head-vs-base regression diff. A failure that exists on both sides produces an empty diff and a green check. Only the push-side absolute check (`scripts/ci/check-failure-baseline.py`, #2247) sees it. So every PR merged since #2487 has shown green, and any new `dev` failure now lands behind an already-red gate. The `v0.9.5-rc4` tag cut (#2838) also sits on this red.

## Acceptance Criteria

- [ ] The four listed files restore `sys.modules` for `services.git_service` **and every `services.git_service.*` submodule** on teardown. Either use a shared helper or match the `startswith` pattern plus restore used in `test_github_init_push.py`.
- [ ] Each command in the repro table passes (89 / 88 / 80 / 88 passed, 0 failed).
- [ ] A regression test named for this issue fails when a test pops only the package key and leaves its submodules cached.
- [ ] `pytest (push, absolute failures)` is green on the `dev` push after the fix, with the 13 IDs **not** added to `tests/unit_failure_baseline.txt`.

## Technical Notes

- Fixing the test files is the root-cause fix. A defensive alternative would make the ent615 fixture load submodules with `importlib.import_module("services.git_service.token_scrub")` instead of reading them as package attributes. That hides the problem in one file and leaves the four polluting files able to break the next test that reads a submodule through the package.
- Related: #1028 (the package split), #2487 (the split PR), #2247 (the absolute-failure gate).

### PR DESCRIPTION
**Pull request by dolho**
Fixes #2859

0.9.5 work order **M1** — the red `dev` (`backend-unit-test` failing on `3a47f74`).

## Root cause
#2487 made `services.git_service` a package. Three test helpers still did `sys.modules.pop("services.git_service")` before re-importing it with stubbed deps — `test_1704_git_service_plugins.py`, `test_data_paths_allowlist.py`, `test_data_paths_gitignore.py`. Evicting only the parent leaves `services.git_service.<sub>` cached, and Python binds a cached submodule onto a **new** parent only on first load — so the re-imported package had no `.token_scrub` / `.conflicts` attribute, and every later `git_service.<sub>` read in `test_ent615_token_free_remotes.py` failed with `AttributeError: module 'services.git_service' has no attribute 'token_scrub'`. 13 failures whenever one of those files runs first (random order under `pytest-randomly`); the file passes alone.

## Fix
Evict the whole `services.git_service*` family (the shape `test_reset_preserve_state_guardrails.py` already uses) at the three sites, and make every parent-only `_restore_sys_modules` fixture family-aware (1704 and both `data_paths` files — a parent restored without its children is the same half-state). Second commit: the fourth polluter from #2859, `test_2075_detect_git_dir.py` (swept the family but recorded only the package key for undo, so the submodules its own re-import created outlived teardown) — now the linter-sanctioned `_STUBBED_MODULE_NAMES` + `_restore_sys_modules` pair.

**Regression guard** (`tests/unit/test_2859_git_service_eviction.py`): the mechanism on a throwaway package (parent-only eviction loses the submodule attribute; family eviction rebinds it) + an AST scan of `tests/unit` that fails on `sys.modules.pop("services.git_service")` / `del sys.modules["services.git_service"]` / `monkeypatch.delitem(sys.modules, "services.git_service")` outside the family shape — self-tested on the exact lines the polluters carried, proven red by reintroducing the pop on a copy.

## Verification
- The issue's repro table (`-p no:randomly`, each polluter then ent615): **13 failed** before on each; after → `test_1704` 102, `test_data_paths_allowlist` 101, `test_data_paths_gitignore` 93, `test_2075` 101 passed, 0 failed.
- `tests/lint_sys_modules.py`: no new violations.
- Full `unit/` with the CI flags (`-n auto --dist loadfile -p randomly`, seed 12345), first commit: **16521 passed, 31 skipped, 0 failed** (11 min). The 13 IDs are **not** added to `tests/unit_failure_baseline.txt`.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by dolho** [comment]
## /review Report

**Branch**: `fix/m1-git-service-stub-leak` → `dev` (merge-base `3a47f74`)
**Files Changed**: 5 (+219/−3), tests only
**Scope**: CLEAN — intent: #2859 (four polluters restore the whole `services.git_service*` family; a named regression test; no baseline entries). Delivered: exactly that. No product code touched.
**Plan Completion** (issue ACs): 3 done / 1 unverifiable
- DONE — four files restore package + submodules: `test_1704_git_service_plugins.py:52-66`, `test_data_paths_allowlist.py:56-70`, `test_data_paths_gitignore.py:53-67` (family snapshot + family-aware `_restore_sys_modules`), `test_2075_detect_git_dir.py:36-59` (new `_STUBBED_MODULE_NAMES` + autouse family restore, teardown after monkeypatch's undo).
- DONE — repro table passes: 102 / 101 / 93 / 101 passed, 0 failed (each polluter then ent615, `-p no:randomly`).
- DONE — regression test named for the issue: `test_2859_git_service_eviction.py` — mechanism on a throwaway package + AST guard; red when the parent-only pop is reintroduced (proven on a copy).
- UNVERIFIABLE from the diff — push-side `pytest (push, absolute failures)` green on `dev`: needs the merge. `tests/unit_failure_baseline.txt` untouched (0-line diff). Local full suite with CI flags, seed 12345: 16521 passed / 0 failed.

### Critical Findings (block merge)
None.

### Informational Findings (review required)

**[I1] Incomplete-fix completeness (4.14): a fifth parent-only eviction lives outside the guard's reach** (Confidence: 8/10)
File: `tests/git_sync/test_s7_reserve_instance_id.py:107`
Evidence: `sys.modules.pop("services.git_service", None)` at module level, followed by `from services import git_service` and `from services.git_service import provisioning`.
Issue: same pattern as the four fixed files. It is outside `tests/unit/`, so it is not in the `backend-unit-test` job and not scanned by the new guard (`TESTS_UNIT.glob("test_*.py")`, `test_2859_git_service_eviction.py:118`). Harmless today — that directory runs alone — but it is the exact line the guard exists to catch, and a future `pytest tests/` invocation would leak it into whatever imports the package next.
Suggestion: follow-up (not this PR — #2859 scopes to `tests/unit`): family-evict there too, and consider widening the guard's glob to `tests/**/test_*.py`.

**[I2] Test gap (4.9): the guard proves the *static* rule; the *runtime* half is proven only by the throwaway-package mechanism test** (Confidence: 6/10)
File: `tests/unit/test_2859_git_service_eviction.py:36-70`
Issue: the mechanism test exercises CPython import semantics on `pkg2859`, not on `services.git_service` itself. If a future `services/git_service/__init__.py` stopped `from .x import …`-ing its submodules, the real package could regress in a way the throwaway package wouldn't show. The static guard still catches the *cause* (parent-only pop), so this is belt-and-braces.
Suggestion: optional — one assertion that, after a family eviction + `import services.git_service`, `hasattr(gs, "token_scrub") and hasattr(gs, "conflicts")` (the two attributes ent615 reads). Cheap; ties the guard to the real package.

**[I3] Consistency (4.7): three copies of the same family-restore block** (Confidence: 5/10 → appendix)
Files: `test_1704:52-66`, `test_data_paths_allowlist:56-70`, `test_data_paths_gitignore:53-67` (+ a fourth variant in `test_2075`).
Issue: identical snapshot/restore code in four files. A conftest fixture would be one copy — but `lint_sys_modules.py` explicitly sanctions the per-file `_STUBBED_MODULE_NAMES` + `_restore_sys_modules` pair, so the duplication is the linter's own shape. Not worth churn in a red-dev fix.

### Clean Categories
- 4.1 SQL / 4.4 credentials / 4.10 frontend / 4.11 perf / 4.12 enums / 4.15 product bar — no product code in the diff.
- 4.2 concurrency — the CI job runs `-n auto --dist loadfile`; `sys.modules` is per-worker-process, and `loadfile` keeps a file on one worker, so the family restore cannot race another file's import. Verified: workflow line `-n auto --dist loadfile`.
- 4.3 auth — n/a.
- 4.8 error handling — fixtures use `try/finally`; the AST guard raises on a parse error (fail-closed) rather than skipping a file.
- 4.13 docs — no architecture/flow surface changed. A `learnings.md` entry for this class ("evicting a package from `sys.modules` must take its submodules") is warranted — not added on this branch per instruction; note for the author.
- `lint_sys_modules.py`: no new violations (the 2075 pair and the guard's own tests use the sanctioned shapes).

### Summary
- Critical: 0 — none found
- Informational: 2 (+1 appendix) — I1 is a follow-up outside this PR's stated scope; I2 optional
- Scope: clean

Review complete. Next: `/validate-pr 2861` for the docs/process pass; file the `tests/git_sync` sibling (I1) as a follow-up.

**Review by obasilakis — APPROVED** [review]
Reviewed at `fc8480cce`. No blocking findings.

- **Repro table on this head** (`-p no:randomly`, each file then ent615): 1704 → 102 passed, allowlist → 101, gitignore → 93, 2075 → 101, 0 failed. The same 1704 → ent615 pair on `dev` fails 13, so the probe does detect the leak.
- **Guard bites:** putting `sys.modules.pop("services.git_service", None)` back into `test_data_paths_gitignore.py` turns `test_no_test_evicts_only_the_git_service_package` red.
- **CI head jobs:** 16524 passed, 0 failed on all three seeds.
- **Teardown order in `test_2075`** is right: the autouse fixture is set up before `monkeypatch`, so it tears down after monkeypatch's undo.

Non-blocking notes:
- `_ALLOWLIST` exempts all of `test_2075_detect_git_dir.py`, so a future parent-only eviction added elsewhere in that file would pass the guard.
- The guard only knows `services.git_service`, but the trap applies to any package. The one other parent-only pop of a package, `services.agent_client` in `test_voice_tools.py:237`, only runs when the key was absent before the test and a stub was installed, and `test_voice_tools` → `test_circuit_breaker` passes (103). So not a live leak today.

**Review by vybe — APPROVED** [review]
merge-train: validated individually against dev 3a47f74 (2-PR run, no train branch). Repro confirmed: each of the four polluters → test_ent615 goes 13 failed → 0 failed; random-order git_service slice clean on seeds 12345/67890/99999.
