### ISSUE TITLE
bug(canvas): every block layout an agent can produce renders unbroken in the workspace column — gallery test + fixes

### ISSUE THREAD

**Issue by vybe** [Abilityai/trinity#2583]
## Summary

The canvas has a rich block vocabulary (ent#536), but it has only ever been looked at through a handful of hand-made canvases. #2581 found that the **first real agent-produced canvas rendered broken** — blocks not laid out in a clean single column, and the column overflowing its width. One broken canvas out of the first few tried is not a single defect; it is an untested render surface.

This issue owns **only the rendering**: take the canvas through *dozens* of different block layouts — every kind, every chart type, every rich fence, and the adversarial shapes an agent will eventually emit — displayed in the **vertical workspace column**, and make each one land correctly. Where a layout breaks, fix the renderer so that class of payload cannot break it again.

**Extracted from #2581.** That issue keeps the voice-mode halves — the missing post-call transcript and the call-mode column split. This one is the UI-only, vocabulary-wide render bar; the two are worked independently.

## Context

The canvas renders through **one** component (`CanvasPanel`) on three surfaces — the Workspace rail Canvas tab (`PortalRailCanvas.vue`), the Workspace agent page (`PortalAgentPage.vue`), and the Agent Detail Canvas tab (`AgentCanvasTab.vue`) — so a fix made once holds everywhere, and a defect missed once is visible everywhere. The narrowest of those, the rail column, is where the layout bar actually bites: the canvas must be *good looking* in a tall, narrow, vertical column, not only in a wide page.

The existing coverage (`e2e/ent438-agent-canvas.spec.js`) asserts that four kinds appear at all. Nothing asserts that they are laid out correctly, that a wide table does not push the page sideways, or that a malformed payload degrades instead of blanking the panel.

**"Unbreakable" is the design-system contract applied to author-controlled content** (`docs/memory/design-system-contract.md`): a block is bounded by its column, unbounded data scrolls *inside its own block*, the page never scrolls horizontally, both themes are first-class, and a payload the renderer cannot make sense of degrades honestly (named reason, JSON fallback) instead of rendering blank or throwing and taking the panel with it.

**Not in scope:** new block kinds, new fences, or changes to the write path / agent prompt guidance. This is render-hardening of the vocabulary that already exists.

## The matrix to cover

Block kinds (`canvasUtils.js`): `table`, `kpi`, `markdown`, `timeline`, `json` (report-delegated) + `chart`, `html`, `image`, `diagram` (canvas-only).

| Dimension | Cases |
|---|---|
| Chart types | `line`, `area`, `bar`, `stacked_bar`, `pie`, `donut` — plus 12-series (palette wrap), single point, all-zero, negative values, missing/null points, long series names |
| Markdown rich fences | `chart`, `kpi`, `table`, `mermaid` inside markdown, several in one block, a fence with a broken body |
| Table | 2 cols vs 12 cols; 200 rows; a 60-char unbroken token in a cell; empty cells; numeric alignment |
| Text | 4000-char paragraph, unbroken URL, CJK, RTL, emoji, a heading-only block |
| Diagram | short flowchart, a 20 000-char source (`CANVAS_DIAGRAM_MAX_CHARS`), a Mermaid source that fails to parse |
| Image | wide landscape, tall portrait, tiny, workspace path that 404s, a refused source |
| html | the voice panel's `update_panel` output, including a long unwrapped line |
| Canvas-level | 1 block, 50 blocks (`CANVAS_MAX_BLOCKS`), a payload near 512 KiB, blocks of mixed kinds interleaved |
| Degradation | unknown kind, kind/payload mismatch, empty payload, `null` fields |

## Acceptance Criteria

- [ ] A **canvas gallery fixture** exists (≥ 12 canvases, ≥ 40 distinct block configurations covering the matrix above), seeded through the **real write path** (`PUT/PATCH /api/agents/{name}/canvas/{canvas_id}`) — not by mounting components with hand-made props — so what is tested is what an agent can actually produce.
- [ ] **Real agent output is part of the evidence, not only the fixture**: at least three canvases asked for from chat in plain language ("dashboard of X", "report with a chart and a table", "diagram of Y") render correctly; screenshots attached to the PR.
- [ ] **No page-level horizontal overflow** on any gallery canvas, in the rail column and full-width surfaces, at 1280 / 1440 / 1920 px and on resize. Wide content (tables, code, diagrams, images, charts) scrolls inside its own block or shrinks to the column.
- [ ] Blocks lay out in **one vertical column** with the kit's spacing on all three surfaces; no block overlaps, clips, or bleeds into its neighbour; no block collapses to zero height.
- [ ] **Light and dark are both correct** for every case — semantic tokens only; `node src/frontend/scripts/scan-raw-colors.mjs src/frontend` does not raise any per-file count over `src/frontend/raw-color-baseline.json`.
- [ ] **Honest degradation**: an unknown kind, a kind/payload mismatch, a malformed fence, or a failing Mermaid parse renders a named fallback (JSON view / reason line) — never a blank block, never a thrown render error that empties the whole panel. One bad block does not stop the good blocks around it from rendering.
- [ ] **Layout stability**: switching canvases, or blocks arriving/refreshing, does not reset scroll position or reflow the surrounding page; the panel reserves space rather than gating the whole surface on a loading flag (`utils/loadingState.js::viewState`).
- [ ] **Playwright coverage** for the gallery: renders at two viewport widths × both themes, asserting no horizontal document overflow and per-block bounding boxes inside the column; screenshots produced as artefacts.
- [ ] Every defect found gets a **regression test** naming its payload class, so the same shape cannot silently return.
- [ ] Findings are recorded: a short table in the PR of "layout tried → what broke → what fixed it", so the render bar is inspectable afterwards.

## Technical Notes

- Renderers: `src/frontend/src/components/canvas/{CanvasPanel,CanvasBlock,CanvasChart,CanvasPieChart,CanvasDiagram,CanvasImage,CanvasMarkdown}.vue`, `canvasUtils.js` (`CANVAS_BLOCK_KINDS`, `CHART_TYPES`, `RICH_FENCES`), `src/frontend/src/utils/canvasPalette.js`.
- Surfaces: `components/portal/PortalRailCanvas.vue` (narrow rail column — the hard case), `components/portal/PortalAgentPage.vue`, `components/canvas/AgentCanvasTab.vue`.
- Report-delegated kinds render through `components/reports/ReportRenderer.vue` — a fix there is shared with reports; keep `shapeOk` inside that component (#1535, #2162).
- Write path / limits: `src/backend/routers/canvas.py`, `services/canvas_blocks.py`, `models.py` (`CANVAS_MAX_BLOCKS=50`, `CANVAS_BLOCKS_MAX_BYTES=512 KiB`, `CANVAS_DIAGRAM_MAX_CHARS=20000`, `CANVAS_IMAGE_INLINE_MAX_BYTES=64 KiB`).
- Existing coverage to extend, not duplicate: `src/frontend/e2e/ent438-agent-canvas.spec.js`, `src/frontend/tests/unit/canvasUtils.spec.js`.
- Bound by `docs/memory/design-system-contract.md`; loading-gate ratchet `src/frontend/loading-gate-baseline.json`.
- Related: #2581 (parent observation, keeps the voice-mode halves), abilityai/trinity-enterprise#536 / #537 (vocabulary, fences, design kit), abilityai/trinity-enterprise#438 (canvas surface).
