### ISSUE TITLE
bug: test_ent183_skill_packages poisons sys.modules — test_ent125_resilient_system_deploy fails collection when run after it

### ISSUE THREAD

**Issue by vybe** [Abilityai/trinity#1855]
## Symptom

On `dev` (e54ce3a9, pre-dates today's merges — reproduced on an untouched checkout):

```
pytest tests/unit/test_ent183_skill_packages.py tests/unit/test_ent125_resilient_system_deploy.py
```

fails at collection:

```
tests/unit/test_ent125_resilient_system_deploy.py:29: in <module>
    import routers.systems as systems
src/backend/services/agent_service/crud.py:37: in <module>
    from services.settings_service import ... resolve_github_pat ...
E   ImportError: cannot import name 'resolve_github_pat' from 'services.settings_service' (unknown location)
```

Both files pass in isolation (60 + 19 tests) and in full-suite order — the collision only appears in this reduced ordering, which is exactly the shape of a targeted "run the touched tests" pre-merge check (how it was found, validating #1845/#1847).

## Cause (hypothesis)

`test_ent183_skill_packages.py` leaves a stub or partially-initialized `services.settings_service` (or a competing `services` package) in `sys.modules`; `(unknown location)` in the ImportError is the tell for a namespace-package/stub left behind. The `lint (sys.modules pollution check)` CI job exists for this class but doesn't catch this pairing.

## Fix shape

Whatever module stubbing ent183 does should be scoped (monkeypatch.setitem on sys.modules, or an explicit teardown restoring the real module), and ideally the pollution-lint extended to catch a `services.*` module left in a non-importable state after a test file completes.
