### PR TITLE
fix(circuit-breaker): only count TCP unreachability toward circuit (#474)

### LINKED ISSUE #474: bug: dropped MCP sync connection causes broken pipe that trips circuit breaker
## Summary

When an MCP synchronous call to an agent is dropped mid-execution (e.g., the MCP client times out or disconnects), the broken HTTP connection propagates as `[Errno 32] Broken pipe` inside the agent's Claude Code runtime. This single event triggers the circuit breaker, which stays open and accumulates failures from subsequent retries/polling on the still-running concurrent executions — eventually opening after 7+ failures and blocking all new task dispatches to the agent, even though the agent container is healthy and the other executions are still running successfully.

## Component

Backend / Agent Client / Circuit Breaker / MCP Server

## Priority

P2

## Error

```
# Agent container log:
ERROR:agent_server.services.claude_code:[Headless Task] Execution error: [Errno 32] Broken pipe

# Backend log sequence:
ERROR services.task_execution_service: [TaskExecService] Failed to execute task on [AGENT]: Task execution error: [Errno 32] Broken pipe
WARNING services.agent_client: Circuit OPENED for agent [AGENT] after 3 failures
WARNING services.agent_client: Circuit OPENED for agent [AGENT] after 4 failures
WARNING services.agent_client: Circuit OPENED for agent [AGENT] after 5 failures
WARNING services.agent_client: Circuit OPENED for agent [AGENT] after 6 failures
WARNING services.agent_client: Circuit OPENED for agent [AGENT] after 7 failures
```

## Timeline

- T+0: Agent is running 2 concurrent executions (slots 1/3 and 2/3)
- T+0: MCP sync call dispatches a 3rd task (slot 3/3)
- T+10s: MCP client connection drops; agent gets EPIPE writing response → HTTP 500
- T+60s onward: Concurrent running executions trigger probe/retry calls → circuit opens repeatedly
- Result: Agent healthy but circuit blocked, no new tasks accepted

## Root Cause

Two interacting issues:

1. **Broken pipe propagation**: When the backend closes its HTTP connection to the agent (due to MCP client disconnect), the agent server gets `EPIPE` trying to write back. This is surfaced as a task execution error rather than a connection-level error, causing it to count against the circuit breaker failure threshold.

2. **Circuit breaker over-sensitivity**: A single EPIPE from a dropped client connection (not an agent health issue) increments the circuit breaker failure counter. The subsequent concurrent executions' completion callbacks are then misinterpreted as additional failures, opening the circuit after only 3 real errors.

## Reproduction Steps

1. Start an agent with 2+ parallel slot capacity
2. Start 2 long-running executions on the agent (filling 2 slots)
3. Make an MCP synchronous call that dispatches a 3rd task to the same agent
4. Drop/cancel the MCP client connection before the task completes
5. Observe `[Errno 32] Broken pipe` error followed by circuit breaker opening
6. Observe the circuit continues to open on subsequent attempts even though the agent container is running fine

## Suggested Fix

Two-pronged fix:

1. **Distinguish connection errors from execution errors**: In the agent client HTTP layer, catch `BrokenPipeError` / `ConnectionResetError` and classify them as connection-level failures rather than execution failures. These should not count toward the circuit breaker threshold, or should count much less aggressively.

2. **Circuit breaker should not re-open on concurrent execution completions**: After the initial EPIPE trip, the circuit breaker should not continue accumulating failures from the completion callbacks of the other still-running (healthy) executions. Consider resetting the circuit to half-open after the first recovery attempt rather than letting concurrent callbacks pile on.

## Environment

- Trinity version: `615a266`
- OS: Ubuntu 22.04

## Related

- Circuit breaker implementation: `services/agent_client.py`
- MCP sync execution path
- Issue #473 (MCP sync attribution bug — same root call)

### PR DESCRIPTION
**Pull request by AndriiPasternak31**
## Summary

Fixes #474. A dropped MCP sync connection used to flip the per-agent circuit breaker because the EPIPE from a half-written response and subsequent `ReadTimeout`s from concurrent pollers were all counted as agent-health failures. The agent was healthy; the circuit was poisoned by client-side / mid-request noise.

## What changed

**`services/agent_client.py`** — single source of truth for failure classification:
- `CIRCUIT_FAILURE_EXCEPTIONS = (httpx.ConnectError, httpx.ConnectTimeout)` — only TCP-level unreachability counts.
- `TRANSIENT_TRANSPORT_EXCEPTIONS` (`ReadTimeout`, `WriteTimeout`, `PoolTimeout`, `WriteError`, `ReadError`, `RemoteProtocolError`) still surface as `AgentNotReachableError` (typed-error contract preserved) but do NOT `record_failure()`.
- Raw `OSError` subclasses (`BrokenPipeError`, `ConnectionResetError`) propagate uncaught — they're local resource bugs, not agent unhealth.
- `asyncio.CancelledError` is re-raised explicitly so shutdown / client-drop cancellation can't be swallowed.
- `is_circuit_failure(exc)` helper exposes the rule for the monitoring service.

**`services/monitoring_service.py`** — the `/health` probe now applies the same rule:
- Imports `CIRCUIT_FAILURE_EXCEPTIONS` / `TRANSIENT_TRANSPORT_EXCEPTIONS` lazily from `agent_client` (with a local fallback to keep circular-import risk at zero).
- Any HTTP response (200..599) records success — symmetric with `_request()`, so stale failure counters clear as soon as the agent proves reachable.
- `aggregate_health()` adds an explicit `network.status_code >= 500 → UNHEALTHY` branch so a wedged-but-listening agent isn't silently rated HEALTHY by the new rule.
- Unexpected exceptions log with traceback and do NOT trip the circuit (unknown errors are almost always our bug).

## Why this shape

The two surfaces (`_request()` and `check_network_health()`) used to apply different rules — one counted timeouts, the other counted 5xx — so the circuit could open from either side depending on which path got there first. They now share `CIRCUIT_FAILURE_EXCEPTIONS` verbatim, which makes the failure-vs-success contract one-line auditable.

The "raw `OSError` subclasses propagate uncaught" choice is deliberate: catching them inside `AgentClientError` would mask local resource bugs (FD exhaustion, kernel-level pipe issues) that are not agent-health signals. Letting them surface loudly is the point.

## Test plan

- [x] `tests/unit/test_circuit_breaker.py` — 12 new cases pinning the `is_circuit_failure()` classifier contract (each exception type asserted individually) + a disjoint-tuples invariant so a future maintainer can't accidentally put the same type in both buckets.
- [x] `tests/integration/test_circuit_breaker.py` — 13 new cases driving the real `AgentClient` through `httpx.MockTransport` against real Redis circuit state. Covers hard failures (ConnectError, ConnectTimeout), soft failures (ReadTimeout × 5 must not trip a threshold-3 circuit, WriteError, raw BrokenPipeError, raw ConnectionResetError, RemoteProtocolError, PoolTimeout), 5xx-records-success, mixed-signal interleave, open-circuit fast-fail (pile-on guard), recovery on 200, and the deferred half-open soft-failure probe-lock behaviour (documented in the test docstring).
- [x] `tests/integration/test_monitoring_service.py` (NEW) — mirrors the classification rule on the `/health` probe path and pins the new `status_code >= 500 → UNHEALTHY` aggregator branch.

## Out of scope

A proper half-open soft-failure counter (so a soft-failure probe releases the lock without tripping the hard threshold) is intentionally deferred — `test_half_open_soft_failure_holds_probe_lock` documents the accepted current behaviour with a pointer to the deferred fix.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by AndriiPasternak31** [comment]
## Local regression evidence

Ran the test plan end-to-end on macOS against a live local stack.

### Before/after on the three PR-targeted test files

| State | Result |
|---|---|
| Pre-fix worktree at `78c6d31f^` = `76bf1502` | unit collection errors with `AttributeError: module 'agent_client' has no attribute 'is_circuit_failure'`; integration: **13 failed, 28 passed** |
| Fix branch (HEAD) | **60 passed, 0 failed** |

The 13 pre-fix failures map 1:1 onto the new contract — exactly the cases the test docstrings pin:

- 6 circuit-breaker classifier cases: `test_read_timeout_does_not_record`, `test_write_error_does_not_record`, `test_remote_protocol_error_does_not_record`, `test_pool_timeout_does_not_record`, `test_mixed_signals_only_hard_failures_count`, `test_half_open_soft_failure_holds_probe_lock`
- 7 monitoring-service cases: `test_503_records_success_returns_reachable`, `test_read_timeout_does_not_record`, `test_read_error_does_not_record`, `test_pool_timeout_does_not_record`, `test_unrelated_exception_does_not_record`, `test_500_status_routes_unhealthy`, `test_503_status_routes_unhealthy`

So the tests genuinely catch the bug — they're not just passing because the implementation passes itself.

### Full regression

- `tests/unit/` — **1403 passed**, 19 failures. All 19 are pre-existing sys.modules-pollution flakes in `test_file_upload.py` / `test_session_persistence_flag.py`: they pass in isolation, and `git log 76bf1502..HEAD -- <path>` shows this PR did not modify either file.
- `/test-runner` over scheduler + top-level + agent/execution + remaining — **0 caused-by-PR failures across ~3000 tests**. 11 additional pre-existing flakes (`test_cb_probe_execution_close.py` cross-pollution when `test_watchdog_unit.py` runs first; `test_subscription_auto_switch.py::test_get_auto_switch_default_on` is state-dependent). 3 pre-existing `trinity_cli` collection errors (CLI package not installed in the test venv).

### `/review`

0 critical, 1 informational (medium confidence): `monitoring_service.py:211-220` hardcodes a fallback list of `CIRCUIT_FAILURE_EXCEPTIONS` / `TRANSIENT_TRANSPORT_EXCEPTIONS` that duplicates the canonical tuples in `agent_client.py:220-237`. It's defensive against a circular import that doesn't exist today; the intent is documented inline. Not blocking — can be deleted, or pinned by a one-line drift-assertion test in a follow-up.

### Verdict

Merge-ready.

**Comment by AndriiPasternak31** [comment]
### Security findings resolution (CSO daily scan 2026-05-12)

Adds three atomic commits to this PR to resolve the findings in `.gstack/security-reports/20260512T230855Z-diff-vulns-secrets.json`:

| Commit | Severity | Title |
|---|---|---|
| ed4cbe8e | CRITICAL | fix(security): sandbox voice panel HTML in iframe |
| 0f8e0569 | HIGH | ci(security): SHA-pin third-party actions, move dev host to secrets |
| dceb1f3a | MEDIUM | chore(governance): add Dependabot + CODEOWNERS, sanitize archived IPs |

**Before merge — operator must:**
- [ ] Set repo secrets `DEV_HOST` (Tailscale node IP for dev — value shared privately) and `DEV_USER` (deploy username — value shared privately) in Settings → Secrets and variables → Actions. Without these the next push to `dev` will fail.
- [ ] **Rotate the Tailscale node IP credential** as well — the original IP was briefly visible in this comment between posting and edit; treat as compromised.
- [ ] Rotate `TAILSCALE_AUTH_KEY` and `DEV_SSH_KEY` proactively — the unpinned-action window has been open since deploy-dev.yml landed.
- [ ] (Optional) Enable branch-protection "require review from code owners" on `main` so the new CODEOWNERS file actually blocks merges, not just auto-requests review.

**After merge:**
- [ ] Re-run `/cso --diff` against `main`. All three fingerprints (`xss-dompurify-allow-scripts-AgentWorkspace.vue:263`, `unpinned-third-party-actions-deploy-dev.yml`, `internal-host-ip-public-repo-deploy-dev.yml:21`) should disappear from `findings[]`.

**Review by vybe — APPROVED** [review]
Clean, focused fix with thorough test coverage. Implementation is one-line auditable — single shared tuple as the source of truth for both call paths. LGTM.
